version: '3.8'

services:
  backend:
    build: ./backend
    container_name: youtube-search-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      # - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - YOUTUBE_API_KEY=AIzaSyDvZa5QTmqdAB0do_K3W5NAeW6di69_3BI
    volumes:
      - ./backend:/app
      # - ./path/to/your/credentials.json:/app/credentials.json
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: 
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://localhost:8000/api
    container_name: youtube-search-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
